### ISSUE TITLE
List elements have to be inside a list

### ISSUE THREAD

**Issue by oliverjam** [fac22/week4-DAM#40]
https://github.com/fac22/week4-DAM/blob/ca192741333c12a4e9ce0fca0aeb49f24241f499/routes/userProfile.js#L34

Probably just an oversight, but `li`s must be inside a `ul` or `ol`

**Comment by Alisyad9** [comment]
thanks Oli for the reminder, thanks for hacking into our database and creating an empty user. 🥇
