### ISSUE TITLE
Signing up should log user in

### ISSUE THREAD

**Issue by oliverjam** [fac22/week4-DAM#41]
https://github.com/fac22/week4-DAM/blob/ca192741333c12a4e9ce0fca0aeb49f24241f499/routes/signup.js#L40

This is more of a UX thing: it's a bit frustrating that after signing up I have to immediately type my email/password again. Since you know who I am at this point you could follow the same process as logging in (create a session, set a cookie, redirect me to the logged in view)

**Comment by lopezelpesado** [comment]
This was an oversight! This was in our plan but we forgot to implement it. One team was working on login and the other on signup, we forgot to implement the login bit for signup once they were done!
